### ISSUE TITLE
No module named configparser

### ISSUE THREAD

**Issue by Ingvix** [boarpig/dyfi.py#3]
Python3 ja requests on asennettuna, mutta antaa otsikon ulostulona, kun koitan lisätä käyttäjää.

**Comment by boarpig** [comment]
Veikkaisin, että järjestelmä ajaa sulla sen kuitenkin python 2:lla, joka on oletus python useissa linux distribuutioissa. Itse kehitin skriptin Archlinuxilla, jossa python linkkaa python3:een.

Puskin uudemman version, joka explisiittisesti vaatii python3:n. Vedäppä uusin version täältä githubista ja kokeile sitä

**Comment by Ingvix** [comment]
No nyt pelittää. Kiitos tästä.
