### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by CodoDerDritte** [boarpig/dyfi.py#4]
Could you add HTTPS-support to this updater? The updates going to the server include usernames and passwords, so using encryption would be kind of important.

**Comment by boarpig** [comment]
dyfi.py already uses HTTPS for updating the IP-address. HTTP is only used for checkip.dy.fi which dy.fi doesn't provide as a HTTPS service.

**Comment by CodoDerDritte** [comment]
Oh, right you are, sorry about that. HTTP for checkip doesn't really matter, because the whole idea of DNS is to connect IPs with domain names :D
