### ISSUE TITLE
Systemd service unit path

### ISSUE THREAD

**Issue by CodoDerDritte** [boarpig/dyfi.py#5]
The path of the executable in the systemd service unit seems to be pointing to home directory of a user. It should point to "standard" FHS-directory for executables, such as /usr/local/bin or /usr/local/sbin. There is a security risk involved in running scripts from users home directories as services.

**Comment by boarpig** [comment]
Thank you! I fixed the systemd point to /usr/bin/dyfi.py and made dyfi.py store config file in /etc as well as make sure the permissions for config file are '-rw-------' so users don't have access to the dy.fi username and password. I wish there was a way to make this without storing username and password, but unfortunately that is a limitation of dy.fi (which is a free service after all)
